sonar.projectKey=akshatkavia-ai_aosp_platform_packages_services_Car-344497
sonar.organization=akshatkavia-ai

sonar.sources=service/src/com/android/car

sonar.sourceEncoding=UTF-8

# Disable heavy Java bytecode requirements
sonar.java.binaries=.

# Reduce analysis load
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-

# Exclusions
sonar.exclusions=**/tests/**,**/out/**,**/.repo/**,**/generated/**

# Optional
sonar.verbose=true
