sonar.projectKey=akshatkavia-ai_aosp_platform_packages_services_Car-344497
sonar.organization=akshatkavia-ai

sonar.sources=service/src/com/android/car

sonar.sourceEncoding=UTF-8

# Disable Java analysis completely
sonar.exclusions=**/*.java

# Ignore huge folders
sonar.coverage.exclusions=**
