sonar.projectKey=akshatkavia-ai_aosp_platform_packages_services_Car-344497
sonar.organization=akshatkavia-ai

sonar.sources=service/src
sonar.tests=tests

sonar.sourceEncoding=UTF-8

# Important for AOSP repos
sonar.java.binaries=.

# Exclude huge/generated folders
sonar.exclusions=**/out/**,**/.repo/**,**/generated/**,**/*.pb.java
